### ISSUE TITLE
Data is not not shown when the php5-mysql is used

### ISSUE THREAD

**Issue by NikitaKunashov** [DevExpress/DevExtreme-PHP-Data#1]
The following error message appears in the server's error.log once the server uses php5-mysql instead of php5-mysqlnd

> [Tue Dec 13 19:43:20.594670 2016] [:error] [pid 18182] [client ::1:57333] PHP Fatal error:  Call to undefined method mysqli_result::fetch_all() in /var/www/DevExtreme/DbSet.php on line 264, referer: http://localhost:10000/

**Comment by NickMitrokhin** [comment]
This is limitation of the [fetch_all](http://php.net/manual/en/mysqli-result.fetch-all.php) method. We will add a note about it in the library description.
