### ISSUE TITLE
Possible SQL injection in the filter string

### ISSUE THREAD

**Issue by NikitaKunashov** [DevExpress/DevExtreme-PHP-Data#2]
It seems that parameters which are composed based on user's input are not properly escaped. For instance, the following input to the filter string (the filter criteria is Equals) causes a delay which means that the sleep method is called: 
> M')) AS a UNION SELECT sleep(25) #

**Comment by NickMitrokhin** [comment]
While we are working on the issue, you can escape special characters in the parameters received from the client side using the [mysqli::real_escape_string](http://php.net/manual/en/mysqli.real-escape-string.php) method. You can do this by passing them to the following function:
```php
function EscapeExpressionValues($mySql, &$expression = NULL) {
        if (isset($expression)) {
            if (is_string($expression)) {
                $expression = $mySql->real_escape_string($expression);
            }
            else if (is_array($expression)) {
                foreach ($expression as &$arr_value) {
                    EscapeExpressionValues($mySql, $arr_value);
                }
                unset($arr_value);
            }
            else if (gettype($expression) === "object") {
                foreach ($expression as $prop => $value) {
                    EscapeExpressionValues($mySql, $expression->$prop);
                }
            }
        }
}
//$mySql  - mysqli instance 
//$params - parameters received from the client side
EscapeExpressionValues($mySql, $params); 
```
Do this before passing parameters to the DbSet methods
