### ISSUE TITLE
Table Valued Parameter implementation(?)

### ISSUE THREAD

**Issue by wcypierre** [DevExpress/DevExtreme-PHP-Data#22]
What I would like to achieve would be conceptually similar to table valued parameter in MSSQL, is there a recommended way to pass a temp table that only exists in the particular connection and pass it into DbSet for joining?

**Comment by NickMitrokhin** [comment]
Hi,

We have never tested this scenario. However, you can try to create a temporary table using the [mysqli](https://www.php.net/manual/book.mysqli.php) extension as shown in the [MySQLi Temporary Tables With PHP](https://stackoverflow.com/questions/34921068/mysqli-temporary-tables-with-php) and pass the reference of this extension and your temporary table to the DbSet constructor.

**Comment by wcypierre** [comment]
Do you have a code sample for this? and where do I pass the main query in this case?

**Comment by NickMitrokhin** [comment]
We do not have the required example. However, you can try the following approach:
```php
$mySQL = new mysqli("serverName", "userName", "password", "databaseName");
//create your temporary table using mysqli
$dbSet = new DbSet($mySQL, "tempraryTableName");
//use any DbSet methods
```
