### ISSUE TITLE
Adapting to use SQL

### ISSUE THREAD

**Issue by lorife** [DevExpress/DevExtreme-PHP-Data#34]
Hello,
I tried your component and it works great when I have to use a standard table. 
However it did not work with SQL. 
My objective was to be able to do:

SELECT *
  FROM table1,
             table2
 WHERE ...

but dbset allow just table names.

So, i tried modifing dbset.php like this:

```
public function __construct($mySQL, $sql, $updateTable) {
        
        $this->mySQL = $mySQL;
        $this->dbTableName = $updateTable;
        $this->resultQuery = $sql;        
    }
```
this way i can use an SQL and when I update I can decide which table I need to update. Devexpress grid for delphi function in the same way. 

Problem is, I think it's not enough to do that, could you take a look and adapt? 
Thank you!

**Comment by NickMitrokhin** [comment]
@lorife 
Would you please describe your final goal in greater detail?

**Comment by lorife** [comment]
Hello, thank you for answering. 

So, i'm going to use about 15 grid in my project. 

Each grid is loaded using a different SQL which takes some parameters from the outside. 
For example, I have a page with an empty grid. The user chooses 2 dates from an external input, click button "search" and I load the grid with those 2 dates as filter. 

The SQL will be something like:

SELECT * 
  FROM orders o,
             companies c
 WHERE o.idcompany=c.idcompany
     AND c.code = :companycode
     AND o.date bewteeen :datefrom and :dateto

then the user will be able to view and EDIT some fields (of course I will allow to edit only fields for one table, in this case "orders"). 
Does it make sense? 

I use developer express grids on delphi and they function in that exact way.

Thanks!

**Comment by NickMitrokhin** [comment]
Thank you for your clarification. We will consider your scenario in future development.

**Comment by lorife** [comment]
Hello Nick,
thank you for answering. It would be great if you could adapt. 
Meanwhile, as with my modification it looks like is working, could you tell me how bad is it to do that?
