### ISSUE TITLE
postgres DB driver AND  DbSet.php file

### ISSUE THREAD

**Issue by hamzeh1388** [DevExpress/DevExtreme-PHP-Data#40]
how connect to postgres DB driver? and DbSet should be change?

**Comment by NickMitrokhin** [comment]
Hi,

At the moment, DevExtreme-PHP-Data does not support PostgreSQL. The current implementation allows you to connect only to MySQL using [mysqli](https://www.php.net/manual/en/book.mysqli.php).

**Comment by hamzeh1388** [comment]
i made it.
:+1:
